version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_db:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "./manage.py makemigrations && ./manage.py migrate && ./manage.py collectstatic
      --no-input && gunicorn -b 0.0.0.0:8000 main.wsgi --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/:/app/staticfiles/
    depends_on:
      - web
      - postgres_db
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_db:
