version: "3.8"

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "./manage.py makemigrations && ./manage.py migrate && ./manage.py collectstatic
      --no-input && gunicorn -b 0.0.0.0:8000 main.wsgi --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db


  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
    depends_on:
      - web
      - db
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data: