# Generated by Django 3.2.8 on 2022-05-14 20:28

import data.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='уберите точку!', regex='\\.$')], verbose_name='Категория')),
                ('img', models.ImageField(blank=True, null=True, upload_to=data.models.category_upload_to, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фио')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('region', models.CharField(choices=[('1', 'Чуй'), ('2', 'Бишкек'), ('3', 'Ош'), ('4', 'Талас'), ('5', 'Иссык куль'), ('6', 'Джалал абад'), ('7', 'Баткен')], max_length=100, verbose_name='Область')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('basket', models.TextField(verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='уберите точку!', regex='\\.$')], verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to=data.models.product_upload_to, verbose_name='Картинка')),
                ('price', models.DecimalField(choices=[('SOM', 'SOM'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('TRY', 'TRY'), ('AED', 'AED')], decimal_places=2, default='SOM', max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('are_available', models.BooleanField(default=True, verbose_name='имеется в наличии')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('sale', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detail', to='data.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='TheSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=6, verbose_name='Размер')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_detail', to='data.product', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(help_text='Отзыв', verbose_name='Отзыв о продукте')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отзыва')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('creview', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.product')),
                ('userview', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('products', models.ManyToManyField(related_name='recommendations_detail', to='data.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'рекомендации',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ImageField(blank=True, null=True, upload_to=data.models.color_upload_to, verbose_name='расцветки')),
                ('color_name', models.CharField(max_length=100, verbose_name='Цвет')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_detail', to='data.product', verbose_name='расцветки')),
            ],
            options={
                'verbose_name': 'Расцветка',
                'verbose_name_plural': 'Расцветки',
            },
        ),
    ]
