# Generated by Django 3.2.8 on 2022-04-21 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='уберите точку!', regex='\\.$')], verbose_name='Категория')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Фио')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('region', models.CharField(choices=[('1', 'Чуй'), ('2', 'Бишкек'), ('3', 'Ош'), ('4', 'Талас'), ('5', 'Иссык куль'), ('6', 'Джалал абад'), ('7', 'Баткен')], max_length=100, verbose_name='Область')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('basket', models.TextField(verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Продукт', max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='уберите точку!', regex='\\.$')], verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=8)], verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('are_available', models.BooleanField(default=True, verbose_name='имеется в наличии')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detail', to='data.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='TheSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=6, verbose_name='Размер')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prod_detail', to='data.product', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('products', models.ManyToManyField(related_name='recommendations_detail', to='data.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'рекомендации',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не менее 1!')], verbose_name='Скидка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_detail', to='data.product')),
            ],
            options={
                'verbose_name': 'Скидкa',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ImageField(blank=True, null=True, upload_to='', verbose_name='расцветки')),
                ('color_name', models.CharField(max_length=100, verbose_name='Цвет')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_detail', to='data.product', verbose_name='расцветки')),
            ],
            options={
                'verbose_name': 'Расцветка',
                'verbose_name_plural': 'Расцветки',
            },
        ),
    ]
