# Generated by Django 3.2.8 on 2022-04-25 06:31

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.category_upload_to, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.color_upload_to, verbose_name='расцветки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=data.models.product_upload_to, verbose_name='Картинка'),
        ),
    ]
