# Generated by Django 4.0.4 on 2022-05-04 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220425_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='уберите точку!', regex='\\.$')], verbose_name='Название'),
        ),
    ]
